Azure/azure-iot-middleware-freertos

source/include/azure_iot.h

Slipped through in prototyping internal header solution

Fix unused header

---

source/include/azure_iot_hub_client.h

1. Rename variables based on coding style.
2. Moved API into feature groups.
3. Added error codes

Update IoTHub header

---

source/azure_iot_hub_client.c
source/include/azure_iot_version.h

Add separate version for middleware

---

source/azure_iot_hub_client.c
source/include/azure_iot_hub_client.h
tests/e2e/device/e2e_device_commands.c
tests/e2e/device/e2e_device_process_commands.h
tests/e2e/device/e2e_device_task.c
tests/ut/azure_iot_cmocka_mqtt.c
tests/ut/azure_iot_hub_client_ut.c

Callback telemetry QOS

---

tests/ut/azure_iot_hub_client_ut.c

Was correct in pnp_wip but I didn't pull it in my bad

Fix hub client ut

---

source/CMakeLists.txt
source/azure_iot_hub_client.c
source/azure_iot_hub_client_properties.c
source/azure_iot_json_reader.c
source/azure_iot_json_writer.c
source/include/azure_iot_hub_client.h
source/include/azure_iot_hub_client_properties.h
source/include/azure_iot_json_reader.h
source/include/azure_iot_json_writer.h
source/include/azure_iot_result.h
tests/e2e/device/e2e_device_commands.c
tests/e2e/device/e2e_device_process_commands.h
tests/e2e/device/e2e_device_task.c
tests/e2e/service/common/e2e_test_core.ts
tests/e2e/service/iothub_client/e2e_iot_hub_client_test.ts
tests/e2e/service/provisioning_client/e2e_iot_provisioning_client_test.ts
tests/ut/CMakeLists.txt
tests/ut/azure_iot_hub_client_properties_ut.c
tests/ut/azure_iot_hub_client_ut.c
tests/ut/azure_iot_json_reader_ut.c
tests/ut/azure_iot_json_writer_ut.c

This takes the staged pnp and merges to master

PnP API Updates

---

.github/workflows/build_docs.yml

fix doxygen build

---

CHANGELOG.md

1.0.0-preview.1 release - changelog update

---

CHANGELOG.md
source/include/azure_iot_version.h

bump version

---

source/azure_iot_hub_client.c
source/azure_iot_hub_client_properties.c

- Updates embedded tag to recently released `1.2.0-beta.1`.
- Updates the function names for a few APIs which were suggested by C SDK core team.

Update embedded tag and use new function names 

---

CHANGELOG.md
source/azure_iot_hub_client.c
source/azure_iot_hub_client_properties.c
source/include/azure_iot_hub_client.h
source/include/azure_iot_hub_client_properties.h
tests/e2e/device/e2e_device_commands.c
tests/ut/azure_iot_hub_client_properties_ut.c
tests/ut/azure_iot_hub_client_ut.c

update naming of requesting the property document

---

CHANGELOG.md
source/azure_iot_private.h
source/include/azure_iot.h

move hmac calculation to private header

---

README.md

closes #198 
closes #197 
closes #196

Update top level readme

---

README.md

add support section

---

CHANGELOG.md

1.0.0 release - changelog update

---

.github/scripts/doxygen.sh

Update to version 1.9.0 since 1.8.17 introduced a regression in the `TYPEDEF_HIDES_STRUCT` option. 1.8.17 is the apt-get version for Ubuntu 20.04.
https://github.com/doxygen/doxygen/issues/7508

Update doxygen gate install

---

source/include/azure_iot_hub_client_properties.h

Thanks to @ryanwinter for the feedback.

add extra docs for property read

---

.github/scripts/ci_tests.sh
.github/scripts/install_software.sh
tests/ut/azure_iot_hub_client_properties_ut.c

add memcheck

---

.github/config/core_http_config.h
.github/workflows/ci_tests_linux.yml
.gitmodules
ports/coreHTTP/azure_iot_core_http.c
ports/coreHTTP/azure_iot_http_port.h
source/CMakeLists.txt
source/azure_iot_adu_client.c
source/azure_iot_hub_client.c
source/include/azure_iot_adu_client.h
source/interface/azure_iot_crypto.h
source/interface/azure_iot_flash_platform.h
source/interface/azure_iot_http.h
tests/config_files/core_http_config.h
tests/e2e/service/common/e2e_test_cleanup.ts
tests/e2e/service/common/e2e_test_core.ts
tests/ut/CMakeLists.txt
tests/ut/azure_iot_adu_client_ut.c

This PR currently points to the `dane/feature/iot-adu` branch of the Embedded C SDK.
https://github.com/Azure/azure-sdk-for-c/pull/2288

add adu code

---

.github/scripts/e2e_tests.sh
.github/scripts/unit_tests.sh
.github/workflows/ci_tests_linux.yml
tests/e2e/Readme.md
tests/e2e/service/common/e2e_test_cleanup.ts
tests/e2e/service/common/e2e_test_core.ts
tests/e2e/service/provisioning_client/e2e_iot_provisioning_client_test.ts

Merge main changes into feature branch

---

source/azure_iot_adu_client.c
source/include/azure_iot_adu_client.h
tests/ut/azure_iot_adu_client_ut.c

Please refer to https://github.com/Azure/azure-sdk-for-c/pull/2331 for details.

Change ADU client update id to match service specification

---

.github/CODEOWNERS
tests/e2e/iot/device/e2e_device_task.c
tests/e2e/iot/service/mocha_exec.sh

Unclean current merge: https://github.com/Azure/azure-iot-middleware-freertos/compare/main...feature/iot-adu?expand=1
What the merge into main will look like once this is merged: https://github.com/Azure/azure-iot-middleware-freertos/compare/main...dane/mergemain?expand=1

Merge main into ADU feature branch

---

README.md

Related to task One\IoT\Platform and Devices\IoT Devices\SDKs\C#16105122

Update samples readme to reference Azure Device Update

---

source/include/azure_iot_hub_client.h

Related issue: https://github.com/Azure/azure-iot-middleware-freertos/issues/232

Improve the function documentation of AzureIoTHubClient_SubscribeCommand and AzureIoTHubClient_UnsubscribeCommand (gh#232)

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml

This might need some adjustments since I could not find a preview viewer.

Add an issue form for bugs
